changed jquery to safe mode in UI (just english for now)
kiwix/kiwix-js pull request #1215
Opened 2024-02-23 12:27 UTC by Greeshmanth1909

#1197
I've changed `Jquery` to `Safe` in the UI. Note that the `s` in `safe mode` is capitalized as it looked much cleaner than the uncapitalized version. 

@Jaifroid  I'll translate the same strings to French and Spanish once you are happy with the changes I've made in English.

2024-02-23 13:31 UTC, Jaifroid requested changes
A good start, thanks! Please note that there will be a bunch of strings in `app.js` and `uiUtil.js`, and possibly others that will also need changing. These are, effectively, the strings in the json file that have IDs beginning with `dialog-`.

2024-02-24 13:01 UTC, Greeshmanth1909 commented
Did a full repo search for `JQuery mode`, `JQuery Mode` and `jquery mode`, the only lines I found were either comments, actual code in automated tests or in `.md` files. I hope I didn't miss anything.

2024-02-26 12:21 UTC, Jaifroid commented
Thanks for this! I'll review and test properly when I get time, but for now I noticed the small issue above.

2024-02-28 11:41 UTC, Greeshmanth1909 commented
What Spanish and French equivalent of "now deprecated" should I remove?

2024-02-28 11:46 UTC, Jaifroid commented
> What Spanish and French equivalent of "now deprecated" should I remove?

Look for the words "obsoleto" (Spanish) and "obsolète" (French).

2024-02-29 17:13 UTC, Greeshmanth1909 commented
The capitalization is a little off. Will fix it asap.

2024-03-02 11:17 UTC, Jaifroid requested changes
Thanks! Some small niggly details with the translations below.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "configure-compatibility-option-jquery": "<strong>Seguro Modo</strong> (No soporta contenido dinámico, compatible con navegadores antiguos)",
```suggestion
      "configure-compatibility-option-serviceworkerlocal": "<strong>ServiceWorkerLocal</strong> (Service Worker local seguro, pero <i>sin ejecución arbitraria de JavaScript</i>)",
      "configure-compatibility-option-serviceworkerlocal-tip": "[Sólo para extensiones de Chromium:] Este modo ejecuta el Service Worker en un sandbox local seguro, y no necesita acceso único a nuestro servidor PWA. Sin embargo, debido a las fuertes restricciones de seguridad en la API, no es capaz de ejecutar todos los fragmentos sueltos de JavaScript, por lo que el contenido ZIM dinámico puede fallar.",
      "configure-compatibility-option-jquery": "<strong>Modo Seguro</strong> (No soporta contenido dinámico, compatible con navegadores antiguos)",
```
The word `seguro` ins ome of these isn't referring to the mode, but is just the adjective "secure", and so shouldn't be capitalized. Also, Safe Mode is "Modo Seguro", not "Seguro Modo".

2024-03-02 11:17 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "dialog-allow-internetaccess-message4": "Necesitamos acceder una sóla vez a nuestro servidor Seguro para que la aplicación pueda volver a iniciarse como una Progressive Web App (PWA). Si está d
Again here, "servidor seguro", not "servidor Seguro". This has nothing to do with the mode. The second "modo Seguro" here is correct.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "dialog-sourceverification-alert": "¿Proviene este archivo ZIM de una fuente de confianza?\nDe no ser así, aún puede leer el archivo en Modo Seguro. Al cerrar esta ventana también se abre el ar
Elsewhere the capitalization is "modo Seguro", but here it is "Modo Seguro". I think change this to "modo Seguro" for consistency.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "about-privacy-long-para1": "Esta aplicación sólo lee los archivos que usted selecciona explícitamente en su dispositivo junto con los archivos del propio paquete del software. Algunos archivos
Again, "seguro" here has notning to do with the mode, and so should not be capitalized.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "about-contentinjection-para3": "<b>Modo ServiceWorkerLocal</b>: Este modo sólo está disponible en las extensiones de Chromium. Es lo mismo que arriba, pero debido a las restricciones de seguri
Ditto, "seguro" here is just an adjective meaning "secure", so don't capitalize.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/fr.jsonp.js
> +      "configure-compatibility-option-serviceworkerlocal": "<strong>Mode ServiceWorkerLocal</strong> (Service Worker local Sécurisé, mais <i>pas d'exécution arbitraire de JavaScript</i>)",
Ditto, the word "sécurisé" here is just an adjective. Don't capitalize.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/fr.jsonp.js
> +      "configure-compatibility-option-serviceworkerlocal-tip": "[Pour les extensions Chromium uniquement&nbsp;:] Ce mode exécute le Service Worker dans un bac à sable local Sécurisé, et n'a pas besoi
Ditto about "sécurisé".

2024-03-02 11:17 UTC, Jaifroid commented on i18n/fr.jsonp.js
> +      "configure-compatibility-option-jquery": "<strong>Sécurisé Mode</strong> (Ne prend pas en charge le contenu dynamique, compatible avec les anciens navigateurs)",
Should be "Mode Sécurisé", not "Sécurisé Mode".

2024-03-02 11:17 UTC, Jaifroid commented on i18n/fr.jsonp.js
> +      "dialog-allow-internetaccess-message4": "avons besoin d'accéder une seule fois à notre serveur Sécurisé pour que l'application puisse redémarrer en tant que Progressive Web App (PWA). Si elle e
First "sécurisé" should not be capitalized. Second should.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/fr.jsonp.js
> +      "dialog-blocked-fileprotocol": "<p>Il semble que vous ouvrez kiwix-js avec le protocole file://, ce qui est bloqué par votre navigateur pour des raisons de sécurité.</p><p>La façon la plus simp
No capitalization for sécurisée.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/fr.jsonp.js
> +      "dialog-serviceworker-registration-failure-fileprotocol": "<br/><br/>Il semble que vous ouvrez kiwix-js avec le protocole file://. Vous devez l'ouvrir avec un serveur Web&nbsp;: soit un serveur
Ditto.

2024-03-02 11:17 UTC, Jaifroid commented on i18n/fr.jsonp.js
> +      "dialog-sourceverification-alert": "Cette archive ZIM provient-elle d'une source fiable&nbsp;? Si ce n'est pas le cas, vous pouvez toujours lire le fichier ZIM en mode Sécurisé (également appel
Delete " (également appelé mode Sécurisé)". This is the old "aka JQuery Mode", which you've changed instead of deleting.

2024-03-02 11:17 UTC, Jaifroid commented on www/js/app.js
> +            '<p>You can continue to use the app in the Safe mode, but note that this mode only works well with ' +
Should be "use the app in Safe mode", not "the".

2024-03-02 11:17 UTC, Jaifroid commented on www/js/app.js
> +                    '<p>You can continue to use the app in the Safe mode, but note that this mode only works well with ' +
Again, remove "the".

2024-03-02 11:21 UTC, Jaifroid commented
Also note that if viewing on GitHub, it hides some of the "conversations" above, and you have to click on "5 hidden conversation ... show more" to see all my suggested corrections.

2024-03-03 18:28 UTC, Greeshmanth1909 commented
Sorry for the delay, had a busy weekend. 
Do note that I've removed `(aka JQuery mode)` in `app.js` as well.

2024-03-04 14:46 UTC, Jaifroid approved these changes
It's looking good, thank you very much! There are the very very last things listed below. While you're doing those, I'll test the UI manually in my browser in the different languages. Then we'll be ready to merge!

2024-03-04 14:46 UTC, Jaifroid commented on www/js/app.js
> +    const response = await uiUtil.systemAlert(translateUI.t('dialog-sourceverification-alert') || "Is this ZIM archive from a trusted source?\n If not, you can still read the ZIM file in Safe Mode. C
Very minor, but our local house style is to use single quotes for strings unless the contents includes an apostrophe, in which case outer double quotes are acceptable. Could you change these double quotes back, please? The ESLint configuration flags these as errors.

2024-03-04 14:46 UTC, Jaifroid commented on i18n/en.jsonp.js
> +      "dialog-sourceverification-alert": "Is this ZIM archive from a trusted source?\n If not, you can still read the ZIM file in Safe Mode (aka Jquery mode). Closing this window also opens the file
Oops, looks like you forgot to get rid of this "(aka Jquery mode)"!

2024-03-04 14:46 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "configure-expert-enable-source-verification-tip": "Advertencia: Algunos archivos ZIM de fuentes no fiables podrían ejecutar código malicioso en tu navegador. Esto puede evitarse utilizando el
I've just noticed that "en tu navegador" should be "en su navegador". (The former is a familiar form of your, but throughout the app we use a more formal form.)

2024-03-04 14:46 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "dialog-serviceworker-defaultmodechange-message": "<p>Le hemos cambiado al modo ServiceWorker (ahora es el modo predeterminado). Soporta más tipos de archivo ZIM y es mucho más robusto.</p><p>S
Remove extraneous space between Seguro and the full stop.

2024-03-04 14:46 UTC, Jaifroid commented on i18n/es.jsonp.js
> +      "about-contentinjection-para4": "<b>Modo Seguro</b>: Este modo impide que los scripts adjuntos se ejecuten en el iframe, por lo que resulta útil para comprobar el contenido estático de un ZIM a
Could you change the second "scripts" in the first sentence to "activos"? It would read better like that.

2024-03-04 16:58 UTC, merged

2024-03-04 17:13 UTC, Greeshmanth1909 commented
Happy to contribute!